accepted = [
  "Apache-2.0",
  "MIT",
  "BSD-3-Clause",
  "ISC",
  "Unicode-3.0",
  "CDLA-Permissive-2.0",
  "Zlib",
  "AGPL-3.0",
  "GPL-3.0",
  "MPL-2.0",
  "AGPL-3.0-or-later",
  "GPL-3.0-or-later",
]
workarounds = ["ring", "chrono", "rustls"]
